import { failWith } from "../errors.js";
import { canonicalJson, sha256Hex } from "./canonical.js";
import type { DeliveryManifest } from "./manifest.js";

/**
 * O5.5C1 — the DELIVERY BUNDLE: exactly the bytes Fusion validated and host-applied into the verified candidate, one entry
 * per create/update operation of the manifest, in operation order — never regenerated by a model. An entry is a regular
 * file's bytes and nothing else: there is no field for a link, a mode, a directory or an absolute path, so a link or
 * reparse entry cannot be expressed. `deliveryBundleSha256` recomputes every entry's content digest from its bytes, so the
 * digest covers the delivered bytes and the metadata; the manifest pins it (`change.bundleSha256`).
 */
export const DELIVERY_BUNDLE_FORMAT = "fusion.deliveryBundle" as const;
export const DELIVERY_BUNDLE_VERSION = 1 as const;

export interface DeliveryBundleEntry {
  readonly index: number;
  readonly path: string;
  readonly sha256: string;
  readonly bytes: number;
  readonly content: Buffer;
}
export interface DeliveryBundle {
  readonly format: typeof DELIVERY_BUNDLE_FORMAT;
  readonly version: typeof DELIVERY_BUNDLE_VERSION;
  readonly deliveryId: string;
  readonly entries: readonly DeliveryBundleEntry[];
}

const tampered = (what: string): never => failWith("SecurityViolation", `The delivery bundle does not match its manifest (${what}).`);
const own = (value: unknown): value is Record<string, unknown> => value !== null && typeof value === "object" && !Array.isArray(value);
const exactKeys = (value: unknown, keys: readonly string[]): value is Record<string, unknown> =>
  own(value) && Object.keys(value).length === keys.length && keys.every(key => Object.hasOwn(value, key));

/** The digest over the bundle's metadata and every entry's content digest, recomputed from the bytes themselves. */
export function deliveryBundleSha256(bundle: DeliveryBundle): string {
  return sha256Hex(canonicalJson({ format: bundle.format, version: bundle.version, deliveryId: bundle.deliveryId,
    entries: bundle.entries.map(entry => ({ index: entry.index, path: entry.path, sha256: sha256Hex(entry.content), bytes: entry.content.length })) }));
}

/**
 * Validates an untrusted bundle against its (validated) manifest: the exact shape, exactly one entry per create/update
 * operation in order with its path and index, bytes whose length and SHA-256 are the manifest's post-image, the caps, and
 * the bundle digest the manifest pins. Returns a copy whose buffers the caller cannot reach. Refused before anything reads
 * or writes a primary.
 */
export function validateDeliveryBundle(value: unknown, manifest: DeliveryManifest): DeliveryBundle {
  if (!exactKeys(value, ["format", "version", "deliveryId", "entries"]) || value.format !== DELIVERY_BUNDLE_FORMAT ||
      value.version !== DELIVERY_BUNDLE_VERSION || value.deliveryId !== manifest.deliveryId || !Array.isArray(value.entries))
    return tampered("shape");
  const writes = manifest.operations.filter(op => op.kind !== "delete");
  if (value.entries.length !== writes.length) return tampered("entry count");
  let total = 0;
  const entries = value.entries.map((entry: unknown, position: number): DeliveryBundleEntry => {
    const op = writes[position]!;
    if (!exactKeys(entry, ["index", "path", "sha256", "bytes", "content"]) || !(entry.content instanceof Uint8Array))
      return tampered("entry shape");
    if (entry.index !== op.index || entry.path !== op.path) return tampered("entry path");
    const content = Buffer.from(entry.content);
    if (content.length > manifest.safety.caps.maxFileBytes || entry.bytes !== content.length || content.length !== op.afterBytes)
      return tampered("entry size");
    const digest = sha256Hex(content);
    if (entry.sha256 !== digest || digest !== op.afterSha256) return tampered("entry content digest");
    total += content.length;
    return Object.freeze({ index: op.index, path: op.path, sha256: digest, bytes: content.length, content });
  });
  if (total > manifest.safety.caps.maxTotalBytes || total !== manifest.change.totalBytes) return tampered("total bytes");
  const bundle: DeliveryBundle = Object.freeze({ format: DELIVERY_BUNDLE_FORMAT, version: DELIVERY_BUNDLE_VERSION, deliveryId: manifest.deliveryId,
    entries: Object.freeze(entries) });
  if (deliveryBundleSha256(bundle) !== manifest.change.bundleSha256) return tampered("bundle digest");
  return bundle;
}

/** A bundle as bytes at rest: canonical JSON with each entry's content in base64. */
export function serializeDeliveryBundle(bundle: DeliveryBundle): string {
  return canonicalJson({ format: bundle.format, version: bundle.version, deliveryId: bundle.deliveryId,
    entries: bundle.entries.map(entry => ({ index: entry.index, path: entry.path, sha256: entry.sha256, bytes: entry.bytes,
      contentBase64: entry.content.toString("base64") })) });
}
/** Parses a serialized bundle back into its shape (still untrusted: `validateDeliveryBundle` decides). */
export function parseDeliveryBundle(text: string): unknown {
  let value: unknown;
  try { value = JSON.parse(text); } catch { return tampered("not JSON"); }
  if (!exactKeys(value, ["format", "version", "deliveryId", "entries"]) || !Array.isArray(value.entries)) return tampered("shape");
  return { format: value.format, version: value.version, deliveryId: value.deliveryId, entries: value.entries.map((entry: unknown) => {
    if (!exactKeys(entry, ["index", "path", "sha256", "bytes", "contentBase64"]) || typeof entry.contentBase64 !== "string" ||
        !/^[A-Za-z0-9+/]*={0,2}$/u.test(entry.contentBase64)) return tampered("entry shape");
    const content = Buffer.from(entry.contentBase64, "base64");
    if (content.toString("base64") !== entry.contentBase64) return tampered("entry encoding");
    return { index: entry.index, path: entry.path, sha256: entry.sha256, bytes: entry.bytes, content };
  }) };
}
